server:
  port: 8080

spring:
  datasource:
    username: root
    password: hb123456
    url: jdbc:mysql://localhost:3306/monitor?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.monitorserver.dto
#showSql
logging:
  level:
    com:
      example:
        mapper : debug

